[target.aarch64-unknown-linux-gnu]
image = "aarch64-unknown-linux-gnu:latest"
linker = "/usr/bin/aarch64-linux-gnu-gcc"

pre-build = [
  "apt-get update",
  "apt-get install -y gcc-aarch64-linux-gnu"
#   "apt-get install -y pkg-config libglib2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-good1.0-dev"
]

[env]
PKG_CONFIG_ALLOW_CROSS = "1"
PKG_CONFIG_SYSROOT_DIR = "/usr/aarch64-linux-gnu"
PKG_CONFIG_PATH = "/usr/lib/aarch64-linux-gnu/pkgconfig"
